set(CMAKE_IMPORT_FILE_VERSION 1)

set(
  JONQUIL_INCLUDEDIRS
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@"
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@/@module-dir@"
)
find_library(
  JONQUIL_LIBRARIES
  "@PROJECT_NAME@"
  PATHS "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@"
  NO_DEFAULT_PATH
)
set(
  JONQUIL_DEPENDENCIES
  "$<$<BOOL:${JONQUIL_USE_TOMLF}>:toml-f::toml-f>"
)

add_library(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE IMPORTED)
add_library(@PROJECT_NAME@::@PROJECT_NAME@ ALIAS @PROJECT_NAME@::@PROJECT_NAME@-lib)
target_link_libraries(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${JONQUIL_LIBRARIES} ${JONQUIL_DEPENDENCIES})
target_include_directories(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${JONQUIL_INCLUDEDIRS})
